const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const SET_MODAL = 'SET_MODAL';
const SET_CHECKBOX_FILTER_CATEGORY = 'SET_CHECKBOX_FILTER_CATEGORY';
const SET_ALL_CATEGORIES = 'SET_ALL_CATEGORIES';
const REMOVE_CHECKBOX_FILTER_CATEGORY = 'REMOVE_CHECKBOX_FILTER_CATEGORY';
const CHANGE_LIST_VIEW = 'CHANGE_LIST_VIEW';
const FETCH_PRODUCTS_FAIL_UPLOAD_FAKE_DATA =
  'FETCH_PRODUCTS_FAIL_UPLOAD_FAKE_DATA';

export {
  FETCH_PRODUCTS_START,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAIL,
  SHOW_MODAL,
  HIDE_MODAL,
  SET_MODAL,
  SET_CHECKBOX_FILTER_CATEGORY,
  SET_ALL_CATEGORIES,
  REMOVE_CHECKBOX_FILTER_CATEGORY,
  CHANGE_LIST_VIEW,
  FETCH_PRODUCTS_FAIL_UPLOAD_FAKE_DATA,
};
