const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
const SHOW_MODAL = 'SHOW_MODAL';
const HIDE_MODAL = 'HIDE_MODAL';
const SET_MODAL = 'SET_MODAL';
const SET_CHECKBOX_FILTER_CATEGORY = 'SET_CHECKBOX_FILTER_CATEGORY';
const REMOVE_CHECKBOX_FILTER_CATEGORY = 'REMOVE_CHECKBOX_FILTER_CATEGORY';

export {
  FETCH_PRODUCTS_START,
  FETCH_PRODUCTS_SUCCESS,
  FETCH_PRODUCTS_FAIL,
  SHOW_MODAL,
  HIDE_MODAL,
  SET_MODAL,
  SET_CHECKBOX_FILTER_CATEGORY,
  REMOVE_CHECKBOX_FILTER_CATEGORY,
};
